package(default_visibility = ["//java/lu/zhe/mtgslackbot:__subpackages__"])

java_library(
    name = "parsing",
    srcs = glob(["*.java"]),
    deps = [
        "//:auto",
        "@com_google_guava_guava//jar",
    ],
)
