package lu.zhe.mtgslackbot.card;

import com.google.common.collect.ImmutableSet;

/**
 * Determines if a card is in the reserve list.
 */
public class ReservedListUtils {
  private ReservedListUtils() {
    // Do not allow instantiation.
  }

  private static final ImmutableSet<String> CANONICAL_NAMES =
      ImmutableSet.of(
          "ancestral recall",
          "badlands",
          "bayou",
          "black lotus",
          "blaze of glory",
          "braingeyser",
          "chaos orb",
          "contract from below",
          "copy artifact",
          "cyclopean tomb",
          "darkpact",
          "demonic attorney",
          "demonic hordes",
          "farmstead",
          "fastbond",
          "forcefield",
          "fork",
          "gauntlet of might",
          "granite gargoyle",
          "illusionary mask",
          "kudzu",
          "lich",
          "mox emerald",
          "mox jet",
          "mox pearl",
          "mox ruby",
          "mox sapphire",
          "natural selection",
          "plateau (brudi)",
          "plateau (tucker)",
          "raging river",
          "roc of kher ridges",
          "rock hydra",
          "savannah",
          "scrubland",
          "sedge troll",
          "taiga",
          "time vault",
          "time walk",
          "timetwister",
          "tropical island",
          "tundra",
          "two-headed giant of foriys",
          "underground sea",
          "vesuvan doppelganger",
          "veteran bodyguard",
          "volcanic island",
          "wheel of fortune",
          "word of command",
          "ali from cairo",
          "bazaar of baghdad",
          "city in a bottle",
          "diamond valley",
          "drop of honey",
          "elephant graveyard",
          "guardian beast",
          "ifh-biff efreet",
          "island of wak-wak",
          "jihad",
          "juzam djinn",
          "khabal ghoul",
          "king suleiman",
          "library of alexandria",
          "merchant ship",
          "old man of the sea",
          "pyramids",
          "ring of maruf",
          "sandals of abdallah",
          "serendib djinn",
          "shahrazad",
          "singing tree",
          "argivian archaeologist",
          "candelabra of tawnos",
          "citanul druid",
          "damping field",
          "gaeas avenger",
          "gate to phyrexia",
          "golgothian sylex",
          "haunting wind",
          "martyrs of korlis",
          "mightstone",
          "mishras workshop",
          "power artifact",
          "powerleech",
          "su-chi",
          "tawnoss coffin",
          "transmute artifact",
          "urzas miter",
          "weakstone",
          "the abyss",
          "acid rain",
          "adun oakenshield",
          "al-abaras carpet",
          "alchors tomb",
          "all hallows eve",
          "angus mackenzie",
          "bartel runeaxe",
          "boris devilboon",
          "caverns of despair",
          "chains of mephistopheles",
          "cleanse",
          "disharmony",
          "divine intervention",
          "elder spawn",
          "eureka",
          "falling star",
          "field of dreams",
          "firestorm phoenix",
          "forethought amulet",
          "gosta dirk",
          "gravity sphere",
          "gwendlyn di corci",
          "halfdane",
          "hazezon tamar",
          "hellfire",
          "imprison",
          "in the eye of chaos",
          "infinite authority",
          "invoke prejudice",
          "jacques le vert",
          "jovial evil",
          "knowledge vault",
          "kobold overlord",
          "lady caleria",
          "lady evangela",
          "land equilibrium",
          "life matrix",
          "lifeblood",
          "living plane",
          "livonya silone",
          "mana matrix",
          "master of the hunt",
          "mirror universe",
          "moat",
          "mold demon",
          "nether void",
          "north star",
          "nova pentacle",
          "pixie queen",
          "planar gate",
          "quarum trench gnomes",
          "ragnar",
          "ramses overdark",
          "rapid fire",
          "rasputin dreamweaver",
          "reverberation",
          "ring of immortals",
          "rohgahh of kher keep",
          "spinal villain",
          "spiritual sanctuary",
          "storm world",
          "sword of the ages",
          "the tabernacle at pendrell vale",
          "telekinesis",
          "tetsuo umezawa",
          "thunder spirit",
          "tuknir deathlock",
          "typhoon",
          "ur-drago",
          "willow satyr",
          "wood elemental",
          "city of shadows",
          "cleansing",
          "eternal flame",
          "exorcist",
          "frankensteins monster",
          "goblin wizard",
          "grave robbers",
          "hidden path",
          "knights of thorn",
          "lurker",
          "mana vortex",
          "martyrs cry",
          "nameless race",
          "niall silvain",
          "preacher",
          "psychic allergy",
          "scarwood bandits",
          "season of the witch",
          "sorrows path",
          "stone calendar",
          "tracker",
          "worms of the earth",
          "wormwood treefolk",
          "aeolipile",
          "balm of restoration",
          "conch horn",
          "delifs cube",
          "draconian cylix",
          "dwarven armorer",
          "ebon praetor",
          "elven lyre",
          "elvish farmer",
          "fungal bloom",
          "goblin flotilla",
          "hand of justice",
          "homarid shaman",
          "icatian lieutenant",
          "icatian skirmishers",
          "implements of sacrifice",
          "rainbow vale",
          "ring of renewal",
          "river merfolk",
          "spirit shield",
          "thelons curse",
          "thelonite monk",
          "thrull champion",
          "tourachs gate",
          "vodalian knights",
          "vodalian war machine",
          "zelyon sword",
          "aegis of the meek",
          "altar of bone",
          "amulet of quoz",
          "balduvian hydra",
          "blizzard",
          "brand of ill omen",
          "call to arms",
          "chromatic armor",
          "earthlink",
          "energy storm",
          "flow of maggots",
          "formation",
          "fyndhorn pollen",
          "general jarkeld",
          "glacial crevasses",
          "gravebind",
          "halls of mist",
          "hot springs",
          "ice cauldron",
          "illusionary presence",
          "illusions of grandeur",
          "infernal denizen",
          "jesters mask",
          "kjeldoran knight",
          "kjeldoran phalanx",
          "land cap",
          "lava tubes",
          "lightning blow",
          "marton stromgald",
          "mercenaries",
          "mesmeric trance",
          "minion of tevesh szat",
          "mountain titan",
          "mudslide",
          "musician",
          "mystic might",
          "polar kraken",
          "reality twist",
          "river delta",
          "ritual of subdual",
          "skeleton ship",
          "snowblind",
          "soldevi golem",
          "spoils of evil",
          "spoils of war",
          "storm spirit",
          "timberline ridge",
          "trailblazer",
          "veldt",
          "winters chill",
          "an-zerrin ruins",
          "anaba ancestor",
          "anaba spirit crafter",
          "apocalypse chime",
          "autumn willow",
          "aysen crusader",
          "aysen highway",
          "bakis curse",
          "baron sengir",
          "beast walkers",
          "black carriage",
          "chain stasis",
          "daughter of autumn",
          "didgeridoo",
          "dwarven pony",
          "dwarven sea clan",
          "faerie noble",
          "grandmother sengir",
          "hazduhr the abbot",
          "heart wolf",
          "koskun falls",
          "leeches",
          "mammoth harness",
          "marjhan",
          "mystic decree",
          "narwhal",
          "reveka, wizard savant",
          "rysorian badger",
          "serra aviary",
          "soraya the falconer",
          "timmerian fiends",
          "veldrane of sengir",
          "wall of kelp",
          "willow priestess",
          "winter sky",
          "ashnods cylix",
          "balduvian trading post",
          "chaos harlequin",
          "dystopia",
          "fatal lore",
          "floodwater dam",
          "gargantuan gorilla",
          "gusthas scepter",
          "heart of yavimaya",
          "helm of obedience",
          "ivory gargoyle",
          "kaysa",
          "keeper of tresserhorn",
          "kjeldoran outpost",
          "krovikan horror",
          "lake of the dead",
          "lodestone bauble",
          "lord of tresserhorn",
          "misfortune",
          "natures wrath",
          "omen of fire",
          "phantasmal sphere",
          "phelddagrif",
          "phyrexian devourer",
          "phyrexian portal",
          "ritual of the machine",
          "rogue skycaptain",
          "royal decree",
          "sheltered valley",
          "soldevi digger",
          "soldevi excavations",
          "splintering wind",
          "sustaining spirit",
          "sworn defender",
          "thawing glaciers",
          "thought lash",
          "tidal control",
          "tornado",
          "varchilds war-riders",
          "wandering mage",
          "winters night",
          "acidic dagger",
          "afiya grove",
          "amulet of unmaking",
          "asmira, holy avenger",
          "auspicious ancestor",
          "barreling attack",
          "bazaar of wonders",
          "benthic djinn",
          "bone mask",
          "brushwagg",
          "cadaverous bloom",
          "canopy dragon",
          "carrion",
          "catacomb dragon",
          "chaosphere",
          "circle of despair",
          "cycle of life",
          "discordant spirit",
          "divine retribution",
          "emberwilde caliph",
          "emberwilde djinn",
          "energy bolt",
          "energy vortex",
          "forsaken wastes",
          "frenetic efreet",
          "grim feast",
          "hakim, loreweaver",
          "hall of gemstone",
          "harbinger of night",
          "hivis of the scale",
          "jabaris influence",
          "jungle patrol",
          "kukemssa pirates",
          "leering gargoyle",
          "lions eye diamond",
          "lure of prey",
          "malignant growth",
          "mangaras tome",
          "mindbender spores",
          "misers cage",
          "mist dragon",
          "natural balance",
          "null chamber",
          "paupers cage",
          "phyrexian dreadnought",
          "phyrexian purge",
          "phyrexian tribute",
          "political trickery",
          "preferred selection",
          "prismatic lace",
          "purgatory",
          "purraj of urborg",
          "rashida scalebane",
          "razor pendulum",
          "reflect damage",
          "reparations",
          "rock basilisk",
          "sawback manticore",
          "seeds of innocence",
          "shallow grave",
          "shauku, endbringer",
          "shimmer",
          "sidar jabari",
          "soul echo",
          "spectral guardian",
          "spirit of the night",
          "subterranean spirit",
          "tainted specter",
          "taniwha",
          "teekas dragon",
          "teferis imp",
          "teferis isle",
          "telimtor",
          "telimtors edict",
          "tombstone stairwell",
          "torrent of lava",
          "unfulfilled desires",
          "ventifact bottle",
          "warping wurm",
          "wellspring",
          "yare",
          "zirilan of the claw",
          "zuberi, golden feather",
          "aku djinn",
          "anvil of bogardan",
          "bogardan phoenix",
          "breathstealers crypt",
          "chronatog",
          "city of solitude",
          "corrosion",
          "diamond kaleidoscope",
          "elkin lair",
          "equipoise",
          "eye of singularity",
          "femeref enchantress",
          "firestorm hellkite",
          "flooded shoreline",
          "forbidden ritual",
          "griffin canyon",
          "guiding spirit",
          "kaerveks spite",
          "katabatic winds",
          "kookus",
          "lichenthrope",
          "lightning cloud",
          "ogre enforcer",
          "phyrexian marauder",
          "pillar tombs of aku",
          "pygmy hippo",
          "quirion druid",
          "rainbow efreet",
          "retribution of the meek",
          "righteous war",
          "sands of time",
          "squandered resources",
          "suleimans legacy",
          "teferis realm",
          "three wishes",
          "tithe",
          "triangle of war",
          "undiscovered paradise",
          "viashivan dragon",
          "zhalfirin crusader",
          "abeyance",
          "aboroth",
          "ancestral knowledge",
          "avizoa",
          "bone dancer",
          "bosium strip",
          "bubble matrix",
          "debt of loyalty",
          "dwarven thaumaturgist",
          "ertais familiar",
          "firestorm",
          "fungus elemental",
          "gallowbraid",
          "goblin bomb",
          "heart of bogardan",
          "heat stroke",
          "infernal tribute",
          "inner sanctum",
          "liege of the hollows",
          "lotus vale",
          "mana web",
          "maraxus of keld",
          "morinfen",
          "mwonvuli ooze",
          "null rod",
          "paradigm shift",
          "peacekeeper",
          "pendrell mists",
          "psychic vortex",
          "scorched ruins",
          "thran tome",
          "tolarian entrancer",
          "tolarian serpent",
          "urborg justice",
          "urborg stalker",
          "wave of terror",
          "well of knowledge",
          "winding canyons",
          "xanthic statue",
          "aluren",
          "apocalypse",
          "avenging angel",
          "commander greven il-vec",
          "corpse dance",
          "cursed scroll",
          "earthcraft",
          "eladamri, lord of leaves",
          "escaped shapeshifter",
          "humility",
          "intuition",
          "meditate",
          "orim, samite healer",
          "recycle",
          "sarcomancy",
          "selenia, dark angel",
          "crovax the cursed",
          "dream halls",
          "mox diamond",
          "silver wyvern",
          "sliver queen",
          "volraths shapeshifter",
          "volraths stronghold",
          "city of traitors",
          "dominating licid",
          "ertai, wizard adept",
          "exalted dragon",
          "hatred",
          "mind over matter",
          "oath of ghouls",
          "recurring nightmare",
          "survival of the fittest",
          "argothian wurm",
          "barrin, master wizard",
          "citanul centaurs",
          "gaeas cradle",
          "gilded drake",
          "great whale",
          "herald of serra",
          "karn, silver golem",
          "lifeline",
          "lightning dragon",
          "morphling",
          "opal archangel",
          "serras sanctum",
          "tolarian academy",
          "temporal aperture",
          "time spiral",
          "yawgmoths will",
          "zephid",
          "deranged hermit",
          "grim monolith",
          "memory jar",
          "multani, maro-sorcerer",
          "palinchron",
          "radiant, archangel",
          "ring of gix",
          "second chance",
          "weatherseed treefolk",
          "academy rector",
          "carnival of souls",
          "covetous dragon",
          "donate",
          "masticore",
          "metalworker",
          "opalescence",
          "phyrexian negator",
          "powder keg",
          "rofellos, llanowar emissary",
          "replenish",
          "treachery",
          "yavimaya hollow",
          "yawgmoths bargain");

  /** Returns true if the canonical name is in the reserved list.*/
  public static boolean isReservedCanonicalName(String canonicalName) {
    return CANONICAL_NAMES.contains(canonicalName);
  }
}
