package(default_visibility = ["//src/main/java/lu/zhe/mtgslackbot:__subpackages__"])

java_library(
    name = "parsing",
    srcs = glob(["*.java"]),
    deps = [
        "//:auto",
        "//src/main/java/lu/zhe/mtgslackbot/card:card",
        "//src/main/java/lu/zhe/mtgslackbot/shared:shared",
        "@com_google_code_findbugs_jsr305//jar",
        "@com_google_guava_guava//jar",
    ],
)
