package(default_visibility = ["//src/main/java/lu/zhe/mtgslackbot:__subpackages__"])

java_library(
    name = "rule",
    srcs = glob(["*.java"]),
    deps = [
        "@com_google_code_gson_gson//jar",
        "@com_google_guava_guava//jar",
    ],
)
