package(default_visibility = ["//src/main/java/lu/zhe/mtgslackbot:__subpackages__"])

java_library(
    name = "rule",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/lu/zhe/mtgslackbot/shared:shared",
        "@com_google_guava_guava//jar",
    ],
)
